name: Deploy
inputs:
  env_aws_secret_name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get relevant environment configuration from aws secrets
      shell: bash
      env:
        SECRET_SSM_NAME: ${{ inputs.env_aws_secret_name }}
        AWS_DEFAULT_REGION: us-west-2
      run: |
        aws secretsmanager get-secret-value --secret-id $SECRET_SSM_NAME --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > .env

    - name: Deploy
      shell: bash
      run: |
        ls -al
        cat .env
        source .env
        echo "$STAGE"
