name: Deploy
on:
  workflow_call:
    inputs:
      env_aws_secret_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - name: Get relevant environment configuration from aws secrets
      env:
        SECRET_SSM_NAME: ${{ inputs.env_aws_secret_name }}
        AWS_DEFAULT_REGION: us-west-2
      run: |
        for s in $(aws secretsmanager get-secret-value --secret-id $SECRET_SSM_NAME --region $AWS_DEFAULT_REGION --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]'); do
          export "${s%=*}=${s#*=}"
        done
    - name: Deploy
      run: echo $STAGE
