name: Diff Infrastructure Changes

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Environment to diff
      IaC:
        required: true
        type: choice
        options:
        - SM2A

jobs:
  plan-sm2a:
    name: '`terraform plan` sm2a'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DIRECTORY: veda-data-airflow
      AWS_REGION: "us-west-2"
      ENVIRONMENT: ${{ inputs.environment }}
    if: ${{ inputs.IaC == 'SM2A' }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:

          submodules: "false"
          persist-credentials: false

      - name: Checkout veda-data-airflow submodule
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: "NASA-IMPACT/${{ env.DIRECTORY }}"
          path: ${{ env.DIRECTORY }}
          ref: ${{ vars.VEDA_SM2A_DATA_AIRFLOW_GIT_REF || 'main'}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c #v6.2.3
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_ARN || secrets.DEPLOYMENT_ROLE_ARN  }}
          role-session-name: "gh-${{ env.ENVIRONMENT }}-airflow-sm2a-deployment"
          aws-region: "${{ env.AWS_REGION }}"

      - name: Run `terraform plan`
        id: plan_sm2a
        uses: "./veda-data-airflow/.github/actions/terraform-deploy-sm2a"
        with:
          env-file: ".env"
          env_aws_secret_name: ${{ vars.SM2A_ENVS_DEPLOYMENT_SECRET_NAME }}
          dir: "${{ env.DIRECTORY }}"
          script_path: "${{ github.workspace }}/scripts/generate_env_file.py"
          run_command: plan
