name: Update Deployment Status

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  update-status-md:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout deployment-state branch
        uses: actions/checkout@v4
        with:
          ref: deployment-state
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run update script
        run: |
          python scripts/update_deployment_status.py \
            --env "${{ inputs.environment }}"
      - name: Commit and push updated deployment-status.md
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deployment-status.md
          git commit -m "Update deployment refs for ${{ inputs.environment }}"
          git push origin deployment-state
